export enum ContentType {
  JSON = "application/json",
  HTML = "text/html",
  PlainText = "text/plain",
  XML = "application/xml",
  FormURLEncoded = "application/x-www-form-urlencoded",
  MultipartFormData = "multipart/form-data",
  JavaScript = "application/javascript",
  CSS = "text/css",
  CSV = "text/csv",
  JPEG = "image/jpeg",
  PNG = "image/png",
  GIF = "image/gif",
  PDF = "application/pdf",
}
